Mach1McleodDynamoTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: omni-mach1-mcleod-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "CONSOL_NBR"
        AttributeType: "S"
      - AttributeName: "processed"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "CONSOL_NBR"
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: processed-index
        KeySchema:
          - AttributeName: processed
            KeyType: HASH
        Projection:
          ProjectionType: 'ALL'