McleodApiLogTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: omni-mcleod-api-log-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
      - AttributeName: "CONSOL_NBR"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: ConsolNBRIndex
        KeySchema:
          - AttributeName: CONSOL_NBR
            KeyType: HASH
        Projection:
          ProjectionType: 'ALL'