Mach1McleodUdpateQueuePolicy:
  Type: 'AWS::SQS::QueuePolicy'
  Properties:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal: 
            Service: "s3.amazonaws.com"
          Action:
            - 'SQS:SendMessage'
          Resource: !GetAtt Mach1McleodUpdateQueue.Arn
          Condition:
            ArnEquals:
              "aws:SourceArn": !Sub "arn:aws:s3:::mach1-mcleod-${self:custom.stage}"
    Queues:
      - Ref: Mach1McleodUpdateQueue



