function:
  name: omni-m1-mcleod-api-${self:provider.stage}
  handler: src/api-function.handler
  description: Omni Mach1 Mcleod
  tags:
    Name: mcleod-api
  package:
    patterns:
      - "!**/*"
      - "src/api-function.js"
      - "src/shared/**"
  runtime: nodejs14.x
  layers:
    - { Ref: OmniMach1McleodLayerLambdaLayer }
  events:
    - schedule: rate(15 minutes)
  timeout: 120
  environment:
    API_ENVIRONMENT: ${self:provider.stage}
    MACH1_MALEOD_TABLE: ${ssm:/omni-mach1-mcleod/${self:provider.stage}/mach1-mcleod/ddb.tableName~true}
    MALEOD_API_LOG_TABLE: ${ssm:/omni-mach1-mcleod/${self:provider.stage}/mcleod-api-plog/ddb.tableName~true}
    MALEOD_API_ENDPOINT: ${ssm:/omni-mach1-mcleod/${self:provider.stage}/mcleod-api-endpoint~true}
    MALEOD_API_USERNAME: ${ssm:/omni-mach1-mcleod/${self:provider.stage}/mcleod-api-username~true}
    MALEOD_API_PASSWORD: ${ssm:/omni-mach1-mcleod/${self:provider.stage}/mcleod-api-password~true}
    MALEOD_API_TOKEN: ${ssm:/omni-mach1-mcleod/${self:provider.stage}/mcleod-api-token~true}
    MALEOD_API_TOPIC_ARN: !Ref McleadApiSnsTopic
    TIMEZONE_TABLE: ${ssm:/omni-wt-rt/airport-timezone/ddb.tableName~true}
  vpc:
    securityGroupIds:
    - ${ssm:/omni-dw/${self:provider.stage}/lambda/sgId}
    subnetIds:
    - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetA}