Mach1McleodSNSTopicPolicy:
  Type: AWS::SNS::TopicPolicy
  Properties:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            Service: 's3.amazonaws.com'
          Action: sns:Publish
          Resource: !Ref Mach1McleodSNSTopic
          Condition:
            ArnEquals:
              Fn::Join:
                - ""
                - - "arn:aws:s3:"
                  - ":"
                  - ":mach1-mcleod-"
                  - ${self:provider.stage}
            StringEquals:
              aws:SourceAccount: !Ref 'AWS::AccountId'
    Topics:
      - !Ref Mach1McleodSNSTopic