stateMachines:
  OmniMcleodStateMachine:
    name: omni-mcleod-state-machine-${self:provider.stage}
    definition:
      StartAt: PublishEvents
      States:
        PublishEvents:
          Type : Task
          Resource : !GetAtt omni_mcleod_fetch_orders.Arn
          Next: EndChoice
        EndChoice:
          Type: Choice
          Choices:
            - Variable: $.finished
              StringEquals: "true"
              Next: SuccessState
          Default: PublishEvents
        SuccessState:
            Type: Succeed
